### PR TITLE
112 provide descriptive database connection error messages

### LINKED ISSUE #112: Provide descriptive database connection error messages
Provide error messages that describe the issue when connecting to a database in Perl modules (e.g. `lib/EFI/Database.pm`).  Some possible cases that should be handled include: invalid module installation on a system level, database connection failed, and database authentication.

### PR DESCRIPTION
**Pull request by nilsoberg**
Add database connection message into code. Added database validation to scripts. Moved database connection to highest level (e.g. at script instead of buried inside modules).

### CODE REVIEW

File: lib/EFI/Database.pm [hunk 1]
```diff
@@ -83,89 +150,262 @@ sub tableExists {
...
+    $sth->execute();
+
+    while (my $row = $sth->fetchrow_hashref()) {
+        processRow($row);
+    }
+
+
+=head3 C<getError()>
+
+Returns an errors that were detected during connection.
```
Comment (rbdavid) [inline lib/EFI/Database.pm]: "any errors"

File: lib/EFI/Database.pm [hunk 2]
```diff
@@ -83,89 +150,262 @@ sub tableExists {
...
+
+=head4 Returns
+
+An empty string of there were no errors, otherwise a non-empty string with
```
Comment (rbdavid) [inline lib/EFI/Database.pm]: "... if there ..."

File: docs/source/lib/EFI/Database.pm.rst [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+
+
+
+SYNOPSIS
+--------
+
+::
+
+   # Perform $gnn computations and save data
+   my $gnn = new EFI::GNT::GNN(...);
```
Comment (rbdavid) [inline docs/source/lib/EFI/Database.pm.rst]: Missing the EFI::Database specific synopsis code block.

File: docs/source/lib/EFI/Database.pm.rst [hunk 4]
```diff
@@ -0,0 +1,220 @@
...
+   while (my $row = $sth->fetchrow_hashref()) {
+       processRow($row);
+   }
+
+
+
+``getError()``
+~~~~~~~~~~~~~~
+
+Returns an errors that were detected during connection.
```
Comment (rbdavid) [inline docs/source/lib/EFI/Database.pm.rst]: "any errors"

File: docs/source/lib/EFI/Database.pm.rst [hunk 5]
```diff
@@ -0,0 +1,220 @@
...
+
+
+
+Returns
+^^^^^^^
+
+An empty string of there were no errors, otherwise a non-empty string
```
Comment (rbdavid) [inline docs/source/lib/EFI/Database.pm.rst]: "... if there..."

File: lib/EFI/Database.pm [hunk 6]
```diff
@@ -83,89 +150,262 @@ sub tableExists {
...
+=head1 EFI::Database
+
+=head2 NAME
+
+B<EFI::Database> - Perl module for creating connections to databases
+
+=head2 SYNOPSIS
+
+    # Perform $gnn computations and save data
+    my $gnn = new EFI::GNT::GNN(...);
```
Comment (rbdavid) [inline lib/EFI/Database.pm]: GNN stuff instead of EFI::Database code.

**Review by rbdavid — APPROVED** [review]
Looks good, just a few grammatical errors and a missing synopsis code block.

**Review by 1ndy — APPROVED** [review]
